# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 3.{build}
configuration: Release
platform: Any CPU

build:
  project: src\EvcProver.sln
  verbosity: normal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)

# branches to build
branches:
  # whitelist
  only:
    - master   
    - rc

skip_tags: true

pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017

artifacts:
  - path: build\Release
    name: EvcProver-v$(appveyor_build_version)-$(APPVEYOR_REPO_BRANCH)
services:
  - mssql2014           # start SQL Server 2014 Express

install:
  - ps: .\src\.nuget\NuGet.exe update -self

deploy:
# Deploy to GitHub Releases
# RC branch
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: v$(APPVEYOR_BUILD_VERSION)
  description: 'v$(APPVEYOR_BUILD_VERSION)'
  auth_token:
    secure: riuun7iAbRmIkLsYhZqe58U99H/PnROepaggimQhrrp8p8gUOCYD2CyrjwvDzPdF
  on:
    branch: rc

